// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY9a0auBV66lMU9-dWtC7DfFaNXzEA0mU',
    appId: '1:391037244507:web:c1739d1db6dc288a8b1b7e',
    messagingSenderId: '391037244507',
    projectId: 'mytask-207bf',
    authDomain: 'mytask-207bf.firebaseapp.com',
    storageBucket: 'mytask-207bf.appspot.com',
    measurementId: 'G-L61EWNQY1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDATXx7GNs2YI-7DKUFBxBwFPvJNRLgWI',
    appId: '1:391037244507:android:f177459e4f4b337f8b1b7e',
    messagingSenderId: '391037244507',
    projectId: 'mytask-207bf',
    storageBucket: 'mytask-207bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTKNwunWUsSGPRnatAG0fZNt7xw2YDFaE',
    appId: '1:391037244507:ios:59a537e09f64f7b48b1b7e',
    messagingSenderId: '391037244507',
    projectId: 'mytask-207bf',
    storageBucket: 'mytask-207bf.appspot.com',
    iosClientId: '391037244507-bs8js3j854hanjfa6ssl1snemmpf92nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTKNwunWUsSGPRnatAG0fZNt7xw2YDFaE',
    appId: '1:391037244507:ios:59a537e09f64f7b48b1b7e',
    messagingSenderId: '391037244507',
    projectId: 'mytask-207bf',
    storageBucket: 'mytask-207bf.appspot.com',
    iosClientId: '391037244507-bs8js3j854hanjfa6ssl1snemmpf92nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytask',
  );
}
